hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 600Mi
  minReplicas: '1'
image:
  imagePullSecrets:
  - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/support-backend
  tag: development-8c4f9fe
networkPolicy:
  allowedServices: []
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1150Mi
  requests:
    cpu: 20m
    memory: 748Mi
service:
  grpcPort: 9090
  port: 8080
  type: ClusterIP
vaultEnv: production
