replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/support-service
  tag: "development-9da1c99"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090
istio:
  enabled: true
  host: "support-service"
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/user-service"
      - "cluster.local/ns/fitnest-dev/sa/identity-service"
      - "cluster.local/ns/fitnest-dev/sa/payment-service"
      - "cluster.local/ns/fitnest-dev/sa/catalog-service"
      - "cluster.local/ns/fitnest-dev/sa/order-service"
      - "cluster.local/ns/fitnest-dev/sa/notifications-service"
      - "cluster.local/ns/fitnest-dev/sa/media-service"
      - "cluster.local/ns/fitnest-dev/sa/fitness-plan-service"
      - "cluster.local/ns/fitnest-dev/sa/api-gateway"
hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "600Mi"
env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRINGDOC_SERVER_URL: "https://dev-api.fitnest.az"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-support:5432/fitnest_support"
  SPRING_DATASOURCE_USERNAME: "fitnest_support"
  SPRING_DATASOURCE_PASSWORD: "support_password_123"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  JWT_SECRET: "your-jwt-secret-change-in-production"
  JWT_ISSUER: "fitnest"
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  USER_SERVICE_URL: "http://user-service:8080"
  JAVA_TOOL_OPTIONS: "-Xms256m -Xmx400m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:MaxMetaspaceSize=128m -Xss512k -XX:+ExitOnOutOfMemoryError"
resources:
  requests:
    cpu: 150m
    memory: 450Mi
  limits:
    cpu: 500m
    memory: 800Mi
